#!/bin/bash
# sync-photo-ids.sh — regenerate extension/photo-ids.js from data-builder/output/index.json
set -euo pipefail
cd "$(dirname "$0")/.."

INDEX="data-builder/output/index.json"
OUT="extension/photo-ids.js"

if [ ! -f "$INDEX" ]; then
  echo "ERROR: $INDEX not found. Run the build (scraper.py / make_sample_data.py) first." >&2
  exit 1
fi

{
  echo "// photo-ids.js — AUTO-GENERATED by scripts/sync-photo-ids.sh"
  echo "// Source: data-builder/output/index.json   Do not edit by hand."
  python3 - "$INDEX" <<'PY'
import sys, json
ids = json.load(open(sys.argv[1]))["photo_ids"]
print("export default " + json.dumps(ids, indent=2) + ";")
PY
} > "$OUT"

COUNT=$(python3 -c "import sys,json; print(len(json.load(open('$INDEX'))['photo_ids']))")
echo "Synced $COUNT photo IDs -> $OUT"
